### ISSUE TITLE
It is a great work! Can you open up your already trained models?

### ISSUE THREAD

**Issue by c1a1o1** [vlgiitr/Group-Level-Emotion-Recognition#4]
Can you open up your already trained models?

**Comment by dakshitagrawal97** [comment]
Hi there @c1a1o1! Thanks for the compliment.  

The trained models can be found in the Google Drive link mentioned inside the respective folders in `TrainedModels` folder.  The models trained on the Full Dataset are in `FullDataset` folder, and models trained on the Train Dataset are in `TrainDataset` folder.

**Comment by dakshitagrawal97** [comment]
Closing this issue. :)

**Comment by c1a1o1** [comment]
Thank you！
