### ISSUE TITLE
The Dataset of Emotiw2018

### ISSUE THREAD

**Issue by P1ckCheN** [vlgiitr/Group-Level-Emotion-Recognition#7]
Hi friend!
I saw the Dataset about Emotiw2018 was not allowed to share, but I really need the Dataset to study and research...  And I cannot find it anywhere .Could you please just help me either give me the Dataset or tell me about how to get it in detail? Thank you very much!!

**Comment by aarushgupta** [comment]
Hi @P1ckCheN 

Please contact the organizers of the challenge for the dataset. You may find the details of the organizers here: https://sites.google.com/view/emotiw2018/organization
