### ISSUE TITLE
How to get the accuracy of the test set

### ISSUE THREAD

**Issue by JiForJoe** [vlgiitr/Group-Level-Emotion-Recognition#8]
The accuracy of the test set in the paper，like "positive 66.59% Neutral57.97%   Negative58.87% Overall 61.84%".Which code file can get such a result?     ：）
I can only get the overall accuracy of each model only on the validation set.
Thank you for your answer

**Comment by dakshitagrawal** [comment]
Hi @JiForJoe!

The test results were given to us by the challenge organizers.  We do not have the test labels to evaluate the models by ourselves.  You may contact the organizers to get the labels for test dataset.  They might provide it, although I am not entirely sure about it.

Thanks!
